[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

remappings = [
  '@chainlink/contracts/=lib/chainlink/contracts/src/',
  '@solmate=lib/solmate/src/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
